stages:
    - fastdl
    - getmmsm
    - deploy
#    - gitguardian
    - github


fastdl:
  stage: fastdl
  script: ionice -c idle nice -19 chrt -i 0 bash ./scripts/fastdl.sh
  only:
    - master
  needs: []
  tags:
    - chi-new

getmmsm:
  stage: getmmsm
  script: ionice -c idle nice -19 chrt -i 0 bash ./scripts/getmmsm.sh
  only:
    - master
  needs: []
  tags:
    - chi-new

deploy:
  stage: deploy
  script: ionice -c idle nice -19 chrt -i 0 bash ./scripts/ci.sh
  only:
    - master
  needs: [getmmsm]
  tags:
    - chi-new

#gitguardian:
#  image: gitguardian/ggshield:latest
#  stage: gitguardian
#  script: ggshield scan ci
#  needs: []
#  tags:
#  - chi-docker
#  only:
#  - master
#

github:
  stage: github
  script: ionice -c idle nice -19 chrt -i 0 bash ./scripts/gh.sh
  only:
    - master
  needs: []
  tags:
    - soplet
